/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.modules.PrimeNumberProcessor

// class App {
//     val greeting: String
//         get() {
//             return "Hello World!"
//         }
// }


fun main() {
    val processor = PrimeNumberProcessor(1..100)

    val resultProcessor = processor.processNumbers()
    
    println("Prime Numbers:")
    resultProcessor.primes.forEach{ it.printValue()}

    println("Odd Numbers:")
    resultProcessor.odds.forEach{ it.printValue()}

    println("Even Numbers:")
    resultProcessor.evens.forEach{ it.printValue()}

    println("Perfect Numbers:")
    resultProcessor.perfects.forEach{ it.printValue()}

    println("Palindrome Numbers:")
    resultProcessor.palindromes.forEach{ it.printValue()}


    // Print some statistics
    println("\nStatistics:")
    println("Total numbers processed: 100")
    println("Number of primes: ${resultProcessor.primes.size}")
    println("Number of odds: ${resultProcessor.odds.size}")
    println("Number of evens: ${resultProcessor.evens.size}")
    println("Number of perfects: ${resultProcessor.perfects.size}")
    println("Number of palindromes: ${resultProcessor.palindromes.size}")


}
